[project]
name = "deepseek-deep-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "arkitect>=0.1.8",
    "gradio>=5.20.1",
    "openai>=1.65.5",
    "python-dotenv>=1.0.1",
    "tavily-python>=0.5.1",
]
